// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudEOak1y_SVxtjxcdP9YiROpnBkFJRzY',
    appId: '1:670852324081:web:95dd50fef828b9ff036750',
    messagingSenderId: '670852324081',
    projectId: 'promociones-de-venta',
    authDomain: 'promociones-de-venta.firebaseapp.com',
    storageBucket: 'promociones-de-venta.firebasestorage.app',
    measurementId: 'G-D8HKNH8VK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAUVGWF5SLeE3u8p-U6pOtorobVYfxEdk',
    appId: '1:670852324081:android:6ca64b0439d82283036750',
    messagingSenderId: '670852324081',
    projectId: 'promociones-de-venta',
    storageBucket: 'promociones-de-venta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALjfv9GJMf0cRmJmsoIgotju-IrWL35wo',
    appId: '1:670852324081:ios:afa06be050541a78036750',
    messagingSenderId: '670852324081',
    projectId: 'promociones-de-venta',
    storageBucket: 'promociones-de-venta.firebasestorage.app',
    iosBundleId: 'com.example.promocionesDeVenta',
  );
}
